SETUP = 'SETUP'
GO = 'GO'
WINNING_PLAY = 'WINNING_PLAY'
PLAYING = 'Playing'
FINISHED = 'Finished'
PLAYERS_QUANTITY_MESSAGE = "How many players?: (A number between 1 and 5)"
PLAYERS_NAME_MESSAGE = "Please, input comma separated names"
NEXT_PLAYER_TURN_MESSAGE = 'Next player turn'
PLAYER_CHOOSING_DICE_MESSAGE = 'Choose dice'
PLAYER_DONE_MESSAGE = 'Your turn is over'
QUANTITY_SET = "Quantity has been set"
INVALID_NUMBER = "Enter a NUMBER!!!!"
PLAYERS_SET = "Players have been set"
