SUCCESS_MESSAGE = 'Your bet was saved succesfully'
NOT_ENOUGH_CASH_MESSAGE = 'You do not have enough cash!'
INVALID_BET_MESSAGE = 'Your bet is invalid'
INVALID_BET_TYPE_MESSAGE = 'Your bet type is invalid'
BYE_MESSAGE = 'Bye'
END_GAME_COMMAND = 'END_GAME'
NEXT_TURN_COMMAND = 'NEXT_TURN'
GO_COMMAND = 'GO'
SELECT_A_TYPE_OF_BET_MESSAGE = " Let's play! choose a type of bet"
